#+TITLE: Developer Notes
* System
These Vagrant images (OVM/OVS) are expected to be packaged together, and communicate over a private network (=intnet=). Furthermore the OVS servers expose multiple private networks. The list of devices networks and servers is given in the the table below:
| Server | Device | VirtualBox Adapter | Network    |
|--------+--------+--------------------+------------|
| OVM    | eth0   |                  1 | NAT        |
|        | eth1   |                  2 | INTNET     |
| OVS    | eth0   |                  1 | NAT        |
|        | eth1   |                  2 | INTNET     |
|        | ethN   |                N+1 | INTNET_N+1 |

Vagrant will modify the =ifcfg-ethN= files to a static address; Server rediscovery will (hopefully!) reset this networking back to whatever is configured for a specific set of machines.
* OVM
OVM is an application installed on top of Oracle Linux. Thus this isn't really part of a Packer build. I need to define a Vagrantfile to build this!
* OVS
OVS is a bare metal install using the Anaconda installer. Packer can handle this.

